CREATE DATABASE TEST_SPRINGBOOT_REST_WS;
GO
USE TEST_SPRINGBOOT_REST_WS;
GO
CREATE LOGIN ADMCONTRACTZIT WITH PASSWORD = 'eNbqetRjVQBcex';
GO
CREATE USER ADMCONTRACTZIT FOR LOGIN ADMCONTRACTZIT;
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [ADMCONTRACTZIT];
GO
